defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
excerpt_separator: "<!-- more -->"
destination: "./docs"
collections:
  sketchbook:
    output: true
  explore:
    output: true