plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/news/page:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "explore"
    values:
      layout: "explore"
excerpt_separator: "<!-- more -->"
destination: "./docs"
collections:
  sketchbook:
    output: true
    sort_by: order
  explore:
    output: true